config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#welcome"

  # Defines the users path route ("/users")
  resources :users do
      resources :events, only: %i[index show create new destroy], controller: 'users/events'
      resources :rooms
      resources :friends, only: %i[index]
      ## Photos could be nested here instead of lines 15/16 but would require changes in testing and wherever those paths are called
      # resources :photos, only: %i[edit update]
  end

  get "/users/:id/photos/edit", to: "users/photos#edit", as: :user_photo_edit
  patch "/users/:id/photos", to: "users/photos#update", as: :update_photo

  patch "/users/:id/update_photo", to: "users#update_photo"

  resources :events, only: %i[index show]
  resources :search, only: %i[index create]
  namespace :search do
    resources :users, only: %i[show create]
  end

  get "search_dashboard", to: "search#search_dashboard", as: :search_dashboard
  get "find_friends", to: "search#find_friends", as: :find_friends
  get "search_results", to: "search#search_results", as: :search_results

  resources :users, only: %i[show], as: :dashboard

  get '/login', to: 'sessions#login_form'
  post '/login', to: 'sessions#login'
  get '/logout', to: 'sessions#logout', as: :logout
  get '/oauth', to: 'goog_sesh#login'
  get '/callback', to: 'goog_sesh#callback'
  get '/users/:user_id/events/:event_id/edit', to: "users/events#edit", as: :event_edit
  patch '/users/:user_id/events/:event_id', to: "users/events#update", as: :event_update
  # delete '/users/:id/events/:id', to: "users/events#destroy", as: :event_destroy
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  def index
    @facade = EventsFacade.new.get_all_events
  end

  def show
    @event = EventsFacade.new.get_one_event(params[:id])
  end

  def new
    @user = params[:user_id]
  end

  private

  def event_params
    params.permit(:title, :description, :street_address, :city, :state, :zipcode, :date_time, :private)
  end
end

app/controllers/search/users_controller.rb
class Search::UsersController < ApplicationController
  def show
    @user = UserFacade.new.find_user(params[:id])
  end

  def create
    RenderService.new.friend_status(params[:user_id], params[:friend_id], params[:status])
    flash[:message] = "Request Sent"
    redirect_to search_results_path
  end

  # def params
  #   params.permit(:friend_id, :user_id, :status)
  # end
end

app/controllers/users/events_controller.rb
class Users::EventsController < ApplicationController
  def index
    @hosting = EventsFacade.new.get_hosting(params[:user_id])
    @attending = EventsFacade.new.get_attending(params[:user_id])
    session[:user_id_event] = params[:user_id]
  end

  def show
    @event = EventsFacade.new.get_one_event(params[:id])
    @user = params[:user_id]
  end

  def new
    @event = EventsFacade.new.get_one_event(params[:event_id])
    @user = params[:user_id]
  end

  def edit
    @event = EventsFacade.new.get_one_event(params[:event_id])
    @user = params[:user_id]
  end

  def update
    EventsFacade.new.update_event(params[:user_id], params[:event_id], event_params)
    redirect_to user_events_path(session[:user_id])
  end

  def create
    user = session[:user_id]
    event_object = EventsFacade.new.create_event(user, event_params)

    client = Signet::OAuth2::Client.new(client_params)
    client.update!(session[:authorization])

    service = Google::Apis::CalendarV3::CalendarService.new
    service.authorization = client
    event = Google::Apis::CalendarV3::Event.new

    event.start = params[:date_time]
    event.summary = params[:title]

    service.insert_event(event_object[:data][0][:id], event)

    redirect_to user_events_path(user)
  end

  def destroy
    EventsFacade.new.delete_an_event(session[:user_id], params[:event_id])
    redirect_to user_events_path(session[:user_id])
    @event = EventsFacade.new.get_one_event(params[:event_id])
    @user = params[:user_id]
  end

  private

  def event_params
    params.permit(:title, :description, :street_address, :city, :state, :zipcode, :date_time, :private)
  end

  def client_params
    {
      client_id: ENV["google_client_id"],
      client_secret: ENV["google_client_secret"],
      authorization_uri: "https://accounts.google.com/o/oauth2/auth",
      token_credential_uri: "https://accounts.google.com/o/oauth2/token",
      scope: Google::Apis::CalendarV3::AUTH_CALENDAR,
      redirect_uri: "https://jana-social-fe.onrender.com/callback"
    }
  end
end

app/controllers/users/photos_controller.rb
class Users::PhotosController < ApplicationController
  def edit
    @user = UserFacade.new.find_user(params[:id])
  end

  def update; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new; end

  def create
    UserFacade.new.create_user(user_create_params)
    flash[:success] = "Your account has been created, go ahead and log in!"
    redirect_to root_path
  end

  def show
    @user = UserFacade.new.find_user(current_user)
  end

  def edit
    @user = UserFacade.new.find_user(params[:id])
  end

  def update
    @user = UserFacade.new.find_user(params[:id])
    if @user.update(user_params)
      redirect_to dashboard_path(@user.id)
    else
      redirect_to edit_user_path(@user.id)
      flash[:notice] = "Data is not valid. Please try again"
    end
  end

  def update_photo
    @user = UserFacade.new.find_user(params[:id])
    UserFacade.new.send_photo(params[:id], params[:file])
    redirect_to edit_user_path(@user.id)
  end
end

private

def user_params
  params.require(:user).permit(:username, :email, :password, :zipcode, :street_address, :bio, :likes, :dislikes, :profile_image_link, :latitude, :longitude)
end

def user_create_params
  params.permit(:username, :email, :password, :zipcode)
end

app/views/users/events/edit.html.erb
<style>
    body {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100vh; /* Ensure the body takes up the full height of the viewport */
    }

    h1 {
      margin-bottom: 20px;
    }

    /* Add any other styling you need for the map and the form */
  </style>

<body>
<div class="container"> <!-- Optional, to center the form -->
  <%= bootstrap_form_tag url: "/users/#{@user}/events/#{@event.id}", method: :patch do |f| %>
    <div class="row">
      <div class="col-md-6">
        <%= f.text_field :title %>
        <%= f.text_area :description %>
        <%= f.text_field :street_address %>
      </div>
      <div class="col-md-6">
        <%= f.text_field :city %>
        <%= f.text_field :state, help: "Must be two character abbreviation" %>
        <%= f.text_field :zipcode %>
        <%= f.datetime_field :date_time %>
        <%= f.check_box :private %>
      </div>
    </div>
    <%= f.submit "Update Event", class: "btn btn-primary" %>
  <% end %>
</div>
</body>


<%= link_to "Delete Event", "/users/#{@user}/events/#{@event.id}", method: :delete %>

app/views/users/events/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Jana Social</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body id="page-top">
  <header class="masthead bg-primary text-white text-center">
      <div class="d-flex align-items-center justify-content-center flex-column" style="height: 20px;">
        <h1 class="masthead-heading mb-0 text-center">Jana Social</h1>
        <div class="divider-custom divider-light">
          <div class="divider-custom-line"></div>
          <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
          <div class="divider-custom-line"></div>
        </div>
      </div>   
  </header>
  <section class="page-section portfolio" id="portfolio" style="background-color: #f2f2f2;">
    <div class="container">
      <div class="text-center">
        <h2 class="page-section-heading text-secondary mb-0 d-inline-block">My Events</h2>
      </div>
      <div class="divider-custom">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
        <div class="divider-custom-line"></div>
      </div>
      <div class="row justify-content-center">
        <section id="hosting-events">
          <h3>Hosting Events</h3>
          <% if @hosting.empty? %>
            <p>You are not hosting any events.</p>
          <% else %>
            <ul>
              <% @hosting.each do |event| %>
                <li>
                  Title: <strong><%= link_to event.title, user_event_path(current_user, event.id) %></strong><br>
                  <%= event.date_time %>
                </li>
              <% end %>
            </ul>
          <% end %>
        </section>
        <section id="attending-events">
          <h3>Attending Events</h3>
          <% if @attending.empty? %>
            <p>You are not attending any events.</p>
          <% else %>
            <ul>
              Title: <% @attending.each do |event| %>
                <li>
                  <strong><%= link_to event.title, event_path(event.id) %></strong>
                  <%= event.date_time %>
                </li>
              <% end %>
            </ul>
          <% end %>
        </section>
      </div>
    </div>
    <div class="d-flex justify-content-center align-items-center">
      <p class="pre-wrap lead mb-0"><%= link_to "Create New Event", oauth_path(current_user), class: "btn btn-primary" %></p>
    </div>
  </section>
</body>
</html>

app/views/users/events/new.html.erb
<style>
    body {
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      height: 100vh; /* Ensure the body takes up the full height of the viewport */
    }

    h1 {
      margin-bottom: 20px;
    }

    /* Add any other styling you need for the map and the form */
  </style>

<body>
<div class="container"> <!-- Optional, to center the form -->
  <%= bootstrap_form_tag url: "/users/#{@user}/events" do |f| %>
    <div class="row">
      <div class="col-md-6">
        <%= f.text_field :title %>
        <%= f.text_area :description %>
        <%= f.text_field :street_address %>
      </div>
      <div class="col-md-6">
        <%= f.text_field :city %>
        <%= f.text_field :state, help: "Must be two character abbreviation" %>
        <%= f.text_field :zipcode %>
        <%= f.datetime_field :date_time %>
        <%= f.check_box :private %>
      </div>
    </div>
    <%= f.submit "Create Event", class: "btn btn-primary" %>
  <% end %>
</div>
</body>

app/views/users/events/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Jana Social</title>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag 'user', media: 'all', 'data-turbolinks-track': 'reload' %>
</head>
<body id="page-top">
  <header class="masthead bg-primary text-white text-center">
    <div class="d-flex align-items-center justify-content-center flex-column" style="height: 20px;">
      <h1 class="masthead-heading mb-0 text-center">Jana Social</h1>
      <div class="divider-custom divider-light">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
        <div class="divider-custom-line"></div>
      </div>
    </div>
  </header>
  <section class="page-section portfolio" id="portfolio" style="background-color: #f2f2f2;">
    <div class="container">
      <div class="text-center">
<h2 class="page-section-heading text-secondary mb-0 d-inline-block">Update Event</h2>
      </div>
      <div class="divider-custom">
        <div class="divider-custom-line"></div>
        <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
        <div class="divider-custom-line"></div>
      </div>
      <div class="row justify-content-center">
        <div class="d-flex justify-content-center align-items-center">
          <p class="pre-wrap lead mb-0">


            <%= link_to "Delete Event", class: "btn btn-primary" %>
          </p>
          <span style="margin: 0 5px;"></span>
          <p class="pre-wrap lead mb-0">
          <%= link_to "Update Event", event_edit_path(@user, @event), class: "btn btn-primary" %>
          </p>
        </div>
      </div>
    </div>
  </section>
</body>
</html>