config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#welcome"

  # Defines the users path route ("/users")
  resources :users do
      resources :events, only: %i[index show create new destroy], controller: 'users/events'
      resources :rooms
      resources :friends, only: %i[index]
      ## Photos could be nested here instead of lines 15/16 but would require changes in testing and wherever those paths are called
      # resources :photos, only: %i[edit update]
  end

  get "/users/:id/photos/edit", to: "users/photos#edit", as: :user_photo_edit
  patch "/users/:id/photos", to: "users/photos#update", as: :update_photo

  patch "/users/:id/update_photo", to: "users#update_photo"

  resources :events, only: %i[index show]
  resources :search, only: %i[index create]
  namespace :search do
    resources :users, only: %i[show create]
  end

  get "search_dashboard", to: "search#search_dashboard", as: :search_dashboard
  get "find_friends", to: "search#find_friends", as: :find_friends
  get "search_results", to: "search#search_results", as: :search_results

  resources :users, only: %i[show], as: :dashboard

  get '/login', to: 'sessions#login_form'
  post '/login', to: 'sessions#login'
  get '/logout', to: 'sessions#logout', as: :logout
  get '/oauth', to: 'goog_sesh#login'
  get '/callback', to: 'goog_sesh#callback'
  get '/users/:user_id/events/:event_id/edit', to: "users/events#edit", as: :event_edit
  patch '/users/:user_id/events/:event_id', to: "users/events#update", as: :event_update
  # delete '/users/:id/events/:id', to: "users/events#destroy", as: :event_destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def current_user
    ## Question: How should we memoize with calling to the backend?
    # @_current_user ||= User.find(session[:user_id]) if session[:user_id]
    @_current_user = session[:user_id]
  end

  def welcome
  end

  private

  def error_message(errors)
    errors.full_messages.join(", ")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/welcome.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">
        <title>Jana Social</title>
        <!-- Font Awesome icons (free version)-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js" crossorigin="anonymous"></script>
        <!-- Core theme CSS (includes Bootstrap)-->
        <!-- Fonts CSS-->
    </head>
    <body id="page-top">
        <header class="masthead bg-primary text-white text-center">
            <div class="d-flex align-items-center justify-content-center flex-column" style="height: 100px;">
            <h1 class="masthead-heading mb-0 text-center">Welcome to Jana Social!</h1>
            <div class="divider-custom divider-light">
                <div class="divider-custom-line"></div>
                <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                <div class="divider-custom-line"></div>
            </div>
<div style="text-align: center; width: 50%; margin: 0 auto;">
  Jana Social is an application for caregivers of adults with disabilities. It is a place for caregivers to connect with other caregivers, share stories, and find events in their area. Jana Social is a place for caregivers to find support and community. Users can create/join events, search for other users, and add friends.
</div>
            </div>
        </header>
        <section class="page-section portfolio" id="portfolio">
            <div class="container">
                <!-- Portfolio Section Heading-->
                <div class="text-center">
                    <h2 class="page-section-heading text-secondary mb-0 d-inline-block">Login</h2>
                </div>
                <!-- Log in User-->
                <div class="divider-custom">
                    <%= bootstrap_form_with url: login_path, method: :post do |f| %>
                        <%= f.email_field :email %>
                        <%= f.password_field :password %>
                        <%= f.submit 'Log In' %>
                    <% end %>
                </div>
                <!-- Create New User-->
                <div class="text-center">
                    <p>Not a member? <a href="<%= new_user_path %>">Create New User</a></p>
                </div>
            </div>
        </section>
    </body>
</html>