config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "application#welcome"

  # Defines the users path route ("/users")
  resources :users do
      resources :events, only: %i[index show create new destroy], controller: 'users/events'
      resources :rooms
      resources :friends, only: %i[index]
      ## Photos could be nested here instead of lines 15/16 but would require changes in testing and wherever those paths are called
      # resources :photos, only: %i[edit update]
  end

  get "/users/:id/photos/edit", to: "users/photos#edit", as: :user_photo_edit
  patch "/users/:id/photos", to: "users/photos#update", as: :update_photo

  patch "/users/:id/update_photo", to: "users#update_photo"

  resources :events, only: %i[index show]
  resources :search, only: %i[index create]
  namespace :search do
    resources :users, only: %i[show create]
  end

  get "search_dashboard", to: "search#search_dashboard", as: :search_dashboard
  get "find_friends", to: "search#find_friends", as: :find_friends
  get "search_results", to: "search#search_results", as: :search_results

  resources :users, only: %i[show], as: :dashboard

  get '/login', to: 'sessions#login_form'
  post '/login', to: 'sessions#login'
  get '/logout', to: 'sessions#logout', as: :logout
  get '/oauth', to: 'goog_sesh#login'
  get '/callback', to: 'goog_sesh#callback'
  get '/users/:user_id/events/:event_id/edit', to: "users/events#edit", as: :event_edit
  patch '/users/:user_id/events/:event_id', to: "users/events#update", as: :event_update
  # delete '/users/:id/events/:id', to: "users/events#destroy", as: :event_destroy
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JanaSocialFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="navbar navbar-expand-sm bg-secondary fixed-top" id="mainNav">
      <img src="/assets/janasocial.png" alt="Janasocial Logo" class="logo">
          <button class="navbar-toggler navbar-toggler-right font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">Menu <i class="fas fa-bars"></i></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto">
                    <li class="nav-item mx-0 mx-lg-1"><%= link_to "Home", root_path %> |
                    <li class="nav-item mx-0 mx-lg-1"><%= link_to "Events", events_path %>
                    </li>
                    <% if current_user %>
                       | <li class="nav-item mx-0 mx-lg-1"><%= link_to "Dashboard", user_path(current_user) %> |
                      </li>
                      <li class="nav-item mx-0 mx-lg-1"><%= link_to "Log Out", logout_path %>
                    <% end %>
                    </li>
                </ul>
            </div>
        </div>
      <% flash.each do |type, msg| %>
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          <div id="flash-messages">
            <%= msg %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
        </div>
      <% end %>
    </nav>
    <%= yield %>
    <% if current_user %>
        <footer class="footer text-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="mb-4">Messages</h4>
                    <p class="pre-wrap lead mb-0"><%= link_to "My Messages", user_rooms_path(current_user), class: "btn btn-primary" %></p>
                </div>
                <div class="col-lg-4 mb-5 mb-lg-0">
                    <h4 class="mb-4">Events</h4>
                    <p class="pre-wrap lead mb-0"><%= link_to "My Events", user_events_path(current_user), class: "btn btn-primary" %></p><br>
                    <p class="pre-wrap lead mb-0"><%= link_to "Discover New Events", events_path, class: "btn btn-primary" %></p>
                </div>
                <div class="col-lg-4">
                    <h4 class="mb-4">Friends</h4>
                    <p class="pre-wrap lead mb-0"><%= link_to "Discover New Friends", search_dashboard_path, class: "btn btn-primary" %></p><br>
                    <p class="pre-wrap lead mb-0"><%= link_to "My Friends", user_friends_path(current_user), class: "btn btn-primary" %></p>
                </div>
            </div>
        </div>
      </footer>
    <% end %>
  </body>
</html>